language: elixir

elixir: '1.5'
otp_release: '19.0'

script:
  # This is basically `mix test` with coverage enabled.
  - mix coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
    - sudo: required
      group: trusty_latest
      services: docker

      script:
        - docker build -t praekeltfoundation/marathon_event_exporter .
      after_script:
        - docker images
